### Create an employee
# @no-log
POST http://localhost:8080/employee
Content-Type: application/json

{
  "employeeId": "007",
  "firstName": "Jacob",
  "lastName": "Sakelarios",
  "position": "Intern",
  "department": "Insurance"
}

### Get an employee
# @no-log
GET http://localhost:8080/employee/62c1084e-6e34-4630-93fd-9153afb65309
Accept: application/json

### Update an employee
# @no-log
PUT http://localhost:8080/employee/62c1084e-6e34-4630-93fd-9153afb65309
Content-Type: application/json

{
  "firstName" : "Pete",
  "lastName" : "Best",
  "position" : "Developer III",
  "department" : "Engineering"
}

### Get direct reports
# @no-log
GET http://localhost:8080/employee/reports/16a596ae-edd3-4847-99fe-c4518e82c86f

### Get reports count
# @no-log
GET http://localhost:8080/employee/reports/16a596ae-edd3-4847-99fe-c4518e82c86f

### Create Compensation
# @no-log
POST http://localhost:8080/compensation
Content-Type: application/json

{
  "employee": "16a596ae-edd3-4847-99fe-c4518e82c86f",
  "salary": 10000000,
  "effectiveDate": "12/6/2023"
}

### Get Compensation
# @no-log
GET http://localhost:8080/compensation/16a596ae-edd3-4847-99fe-c4518e82c86f
